name: Build Music Player

on:
  push:
    tags:
      - 'v*'  # triggers on any tag starting with "v", e.g., v1.0, v2.3.1

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 24
      - run: ./gradlew jpackageMac

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 24
      - run: .\gradlew jpackageWin

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 24
      - run: ./gradlew jpackageLinux
