name: Build Music Player JAR

on:
  push:
    tags:
      - 'v*'  # triggers on any tag starting with "v", e.g., v1.0, v2.3.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 24

      - name: Build Jar
        run: ./gradlew clean build
      
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: MusicPlayer-JAR
          path: build/libs/ArchipelagoMusicClient-*.jar
