name: Build Music Player JAR

on:
  push:
    tags:
      - 'v*'  # triggers on any tag starting with "v", e.g., v1.0, v2.3.1
  workflow_call:  # Add this line to allow other workflows to call it

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 25

      - name: Strip leading v from version
        id: version
        run: |
          ver="${{ github.event.inputs.version || github.ref_name }}"
          echo "version_no_v=${ver#v}" >> $GITHUB_OUTPUT

      - name: Build Jar
        run: ./gradlew clean build -PappVersion=${{ steps.version.outputs.version_no_v }}
      
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: MusicPlayer-JAR
          path: build/libs/ArchipelagoMusicClient-*-all.jar
